"""
This module contains the Expr class and its subclasses.
Generated by generate_ast.py
"""

from abc import ABC
from spamoji.token import Token


class Expr(ABC):
    """Base class for all exprs."""
    def accept(self, visitor: "Visitor") -> object:
        pass


class Visitor(ABC):
    def visit_assign_expr(self, expr: "Assign") -> object:
        pass
    def visit_binary_expr(self, expr: "Binary") -> object:
        pass
    def visit_call_expr(self, expr: "Call") -> object:
        pass
    def visit_get_expr(self, expr: "Get") -> object:
        pass
    def visit_set_expr(self, expr: "Set") -> object:
        pass
    def visit_this_expr(self, expr: "This") -> object:
        pass
    def visit_super_expr(self, expr: "Super") -> object:
        pass
    def visit_logical_expr(self, expr: "Logical") -> object:
        pass
    def visit_if_expr(self, expr: "If") -> object:
        pass
    def visit_grouping_expr(self, expr: "Grouping") -> object:
        pass
    def visit_literal_expr(self, expr: "Literal") -> object:
        pass
    def visit_unary_expr(self, expr: "Unary") -> object:
        pass
    def visit_variable_expr(self, expr: "Variable") -> object:
        pass


class Assign(Expr):
    """Represents a assign expression."""

    def __init__(self, name: Token, value: Expr):
        self.name = name
        self.value = value

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_assign_expr(self)


class Binary(Expr):
    """Represents a binary expression."""

    def __init__(self, left: Expr, operator: Token, right: Expr):
        self.left = left
        self.operator = operator
        self.right = right

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_binary_expr(self)


class Call(Expr):
    """Represents a call expression."""

    def __init__(self, callee: Expr, paren: Token, arguments: list[Expr]):
        self.callee = callee
        self.paren = paren
        self.arguments = arguments

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_call_expr(self)


class Get(Expr):
    """Represents a get expression."""

    def __init__(self, obj: Expr, name: Token):
        self.obj = obj
        self.name = name

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_get_expr(self)


class Set(Expr):
    """Represents a set expression."""

    def __init__(self, obj: Expr, name: Token, value: Expr):
        self.obj = obj
        self.name = name
        self.value = value

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_set_expr(self)


class This(Expr):
    """Represents a this expression."""

    def __init__(self, keyword: Token):
        self.keyword = keyword

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_this_expr(self)


class Super(Expr):
    """Represents a super expression."""

    def __init__(self, keyword: Token, method: Token):
        self.keyword = keyword
        self.method = method

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_super_expr(self)


class Logical(Expr):
    """Represents a logical expression."""

    def __init__(self, left: Expr, operator: Token, right: Expr):
        self.left = left
        self.operator = operator
        self.right = right

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_logical_expr(self)


class If(Expr):
    """Represents a if expression."""

    def __init__(self, condition: Expr, then_branch: Expr, else_branch: Expr):
        self.condition = condition
        self.then_branch = then_branch
        self.else_branch = else_branch

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_if_expr(self)


class Grouping(Expr):
    """Represents a grouping expression."""

    def __init__(self, expression: Expr):
        self.expression = expression

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_grouping_expr(self)


class Literal(Expr):
    """Represents a literal expression."""

    def __init__(self, value: object):
        self.value = value

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_literal_expr(self)


class Unary(Expr):
    """Represents a unary expression."""

    def __init__(self, operator: Token, right: Expr):
        self.operator = operator
        self.right = right

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_unary_expr(self)


class Variable(Expr):
    """Represents a variable expression."""

    def __init__(self, name: Token):
        self.name = name

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_variable_expr(self)
