"""
AST Generator
"""

import sys


def main():
    """Main entry point."""
    if len(sys.argv) != 2:
        print("Usage: generate_ast <output_directory>")
        sys.exit(64)
    output_dir = sys.argv[1]
    define_ast(
        output_dir,
        "Expr",
        [
            "Binary   @ left: Expr, operator: Token, right: Expr",
            "Grouping @ expression: Expr",
            "Literal  @ value: object",
            "Unary    @ operator: Token, right: Expr",
        ],
    )


def define_ast(output_dir: str, base_name: str, types: list[str]):
    path = f"{output_dir}/{base_name.lower()}.py"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            f'"""\nThis module contains the {base_name} class and its subclasses.\n'
        )
        f.write(f'Generated by generate_ast.py\n"""\n\n')
        f.write("from abc import ABC\n\n")
        f.write("from interpreter.token import Token\n\n\n")
        f.write(f"class {base_name}(ABC):\n")
        f.write(f'    """Base class for all {base_name.lower()}s."""\n')
        for type in types:
            class_name, fields = type.split("@")
            class_name = class_name.strip()
            fields = fields.strip()
            define_type(f, base_name, class_name, fields)


def define_type(f, base_name: str, class_name: str, fields: str):
    f.write(f"\n\nclass {class_name}({base_name}):\n")
    f.write(f'    """Represents a {class_name.lower()} expression."""\n\n')
    f.write(f"    def __init__(self, {fields}):\n")
    for field in fields.split(","):
        name = field.strip().split(":")[0]
        f.write(f"        self.{name} = {name}\n")


if __name__ == "__main__":
    main()
