"""
AST Generator
"""

import sys


def main():
    """Main entry point."""
    if len(sys.argv) != 2:
        print("Usage: generate_ast <output_directory>")
        sys.exit(64)
    output_dir = sys.argv[1]
    define_ast(
        output_dir,
        "Expr",
        [
            "Binary   @ left: Expr, operator: Token, right: Expr",
            "Grouping @ expression: Expr",
            "Literal  @ value: object",
            "Unary    @ operator: Token, right: Expr",
            "Variable @ name: Token",
        ],
        imports=["from interpreter.token import Token"],
    )
    define_ast(
        output_dir,
        "Stmt",
        [
            "Expression @ expression: Expr",
            "Python     @ expression: Expr",
            "Variable   @ name: Token, initializer: Expr",
        ],
        imports=["from interpreter.expr import Expr"],
    )


def define_ast(
    output_dir: str, base_name: str, types: list[str], imports: list[str] | None = None
):
    path = f"{output_dir}/{base_name.lower()}.py"
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            f'"""\nThis module contains the {base_name} class and its subclasses.\n'
        )
        f.write(f'Generated by generate_ast.py\n"""\n\n')
        f.write("from abc import ABC\n")
        for import_stmt in imports or []:
            f.write(f"{import_stmt}\n")
        f.write("\n\n")
        f.write(f"class {base_name}(ABC):\n")
        f.write(f'    """Base class for all {base_name.lower()}s."""\n')
        f.write('    def accept(self, visitor: "Visitor") -> object:\n')
        f.write("        pass\n\n\n")
        define_visitor(f, base_name, types)
        for type in types:
            class_name, fields = type.split("@")
            class_name = class_name.strip()
            fields = fields.strip()
            define_type(f, base_name, class_name, fields)


def define_type(f, base_name: str, class_name: str, fields: str):
    f.write(f"\n\nclass {class_name}({base_name}):\n")
    f.write(f'    """Represents a {class_name.lower()} expression."""\n\n')
    f.write(f"    def __init__(self, {fields}):\n")
    for field in fields.split(","):
        name = field.strip().split(":")[0]
        f.write(f"        self.{name} = {name}\n")
    f.write("\n")
    f.write("    def accept(self, visitor: Visitor) -> object:\n")
    f.write(
        f"        return visitor.visit_{class_name.lower()}_{base_name.lower()}(self)\n"
    )


def define_visitor(f, base_name: str, types: list[str]):
    f.write(f"class Visitor(ABC):\n")
    for t in types:
        type_name = t.split("@")[0].strip()
        f.write(f"    def visit_{type_name.lower()}_{base_name.lower()}(")
        f.write(f'self, {base_name.lower()}: "{type_name}") -> object:\n')
        f.write(f"        pass\n")


if __name__ == "__main__":
    main()
