"""
This module contains the Expr class and its subclasses.
Generated by generate_ast.py
"""

from abc import ABC
from interpreter.token import Token


class Expr(ABC):
    """Base class for all exprs."""
    def accept(self, visitor: "Visitor") -> object:
        pass


class Visitor(ABC):
    def visit_binary_expr(self, expr: "Binary") -> object:
        pass
    def visit_grouping_expr(self, expr: "Grouping") -> object:
        pass
    def visit_literal_expr(self, expr: "Literal") -> object:
        pass
    def visit_unary_expr(self, expr: "Unary") -> object:
        pass
    def visit_variable_expr(self, expr: "Variable") -> object:
        pass


class Binary(Expr):
    """Represents a binary expression."""

    def __init__(self, left: Expr, operator: Token, right: Expr):
        self.left = left
        self.operator = operator
        self.right = right

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_binary_expr(self)


class Grouping(Expr):
    """Represents a grouping expression."""

    def __init__(self, expression: Expr):
        self.expression = expression

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_grouping_expr(self)


class Literal(Expr):
    """Represents a literal expression."""

    def __init__(self, value: object):
        self.value = value

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_literal_expr(self)


class Unary(Expr):
    """Represents a unary expression."""

    def __init__(self, operator: Token, right: Expr):
        self.operator = operator
        self.right = right

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_unary_expr(self)


class Variable(Expr):
    """Represents a variable expression."""

    def __init__(self, name: Token):
        self.name = name

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_variable_expr(self)
