"""
This module contains the Expr class and its subclasses.
Generated by generate_ast.py
"""

from abc import ABC

from interpreter.token import Token


class Expr(ABC):
    """Base class for all exprs."""


class Binary(Expr):
    """Represents a binary expression."""

    def __init__(self, left: Expr, operator: Token, right: Expr):
        self.left = left
        self.operator = operator
        self.right = right


class Grouping(Expr):
    """Represents a grouping expression."""

    def __init__(self, expression: Expr):
        self.expression = expression


class Literal(Expr):
    """Represents a literal expression."""

    def __init__(self, value: object):
        self.value = value


class Unary(Expr):
    """Represents a unary expression."""

    def __init__(self, operator: Token, right: Expr):
        self.operator = operator
        self.right = right
