"""
This module contains the Stmt class and its subclasses.
Generated by generate_ast.py
"""

from abc import ABC
from interpreter.expr import Expr


class Stmt(ABC):
    """Base class for all stmts."""
    def accept(self, visitor: "Visitor") -> object:
        pass


class Visitor(ABC):
    def visit_expression_stmt(self, stmt: "Expression") -> object:
        pass
    def visit_python_stmt(self, stmt: "Python") -> object:
        pass


class Expression(Stmt):
    """Represents a expression expression."""

    def __init__(self, expression: Expr):
        self.expression = expression

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_expression_stmt(self)


class Python(Stmt):
    """Represents a python expression."""

    def __init__(self, expression: Expr):
        self.expression = expression

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_python_stmt(self)
