"""
This module contains the Stmt class and its subclasses.
Generated by generate_ast.py
"""

from abc import ABC
from interpreter.expr import Expr
from interpreter.token import Token


class Stmt(ABC):
    """Base class for all stmts."""
    def accept(self, visitor: "Visitor") -> object:
        pass


class Visitor(ABC):
    def visit_block_stmt(self, stmt: "Block") -> object:
        pass
    def visit_expression_stmt(self, stmt: "Expression") -> object:
        pass
    def visit_if_stmt(self, stmt: "If") -> object:
        pass
    def visit_while_stmt(self, stmt: "While") -> object:
        pass
    def visit_loopctrl_stmt(self, stmt: "LoopCtrl") -> object:
        pass
    def visit_python_stmt(self, stmt: "Python") -> object:
        pass
    def visit_variable_stmt(self, stmt: "Variable") -> object:
        pass


class Block(Stmt):
    """Represents a block expression."""

    def __init__(self, statements: list[Stmt]):
        self.statements = statements

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_block_stmt(self)


class Expression(Stmt):
    """Represents a expression expression."""

    def __init__(self, expression: Expr):
        self.expression = expression

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_expression_stmt(self)


class If(Stmt):
    """Represents a if expression."""

    def __init__(self, condition: Expr, then_branch: Stmt | None, else_branch: Stmt | None):
        self.condition = condition
        self.then_branch = then_branch
        self.else_branch = else_branch

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_if_stmt(self)


class While(Stmt):
    """Represents a while expression."""

    def __init__(self, condition: Expr, body: Stmt):
        self.condition = condition
        self.body = body

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_while_stmt(self)


class LoopCtrl(Stmt):
    """Represents a loopctrl expression."""

    def __init__(self, type: Token):
        self.type = type

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_loopctrl_stmt(self)


class Python(Stmt):
    """Represents a python expression."""

    def __init__(self, expression: Expr):
        self.expression = expression

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_python_stmt(self)


class Variable(Stmt):
    """Represents a variable expression."""

    def __init__(self, name: Token, initializer: Expr | None):
        self.name = name
        self.initializer = initializer

    def accept(self, visitor: Visitor) -> object:
        return visitor.visit_variable_stmt(self)
